// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package example.proto.message

object MessageProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      example.proto.message.NumberBuffer
    )
  private lazy val ProtoBytes: Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """CiBzcmMvbWFpbi9yZXNvdXJjZXMvbWVzc2FnZS5wcm90bxIGcHJvdG8zIrgBCgxOdW1iZXJCdWZmZXISFwoCaWQYASABKANCB
  +I/BBICaWRSAmlkEiwKCXRpbWVzdGFtcBgCIAEoA0IO4j8LEgl0aW1lc3RhbXBSCXRpbWVzdGFtcBIdCgRuYW1lGAMgASgJQgniP
  wYSBG5hbWVSBG5hbWUSIwoGbnVtYmVyGAQgASgFQgviPwgSBm51bWJlclIGbnVtYmVyEh0KBHR5cGUYBSABKAlCCeI/BhIEdHlwZ
  VIEdHlwZUIPCg1leGFtcGxlLnByb3RvYgZwcm90bzM="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor =
    example.proto.Message.getDescriptor()
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}
